stages:
  - compiling
  - publishing

Compile Firefox:
  stage: compiling
  script:
    - mkdir dist
    - npm install
    - npm run build:firefox
    - mv build dist/firefox-extension
  artifacts:
    paths:
      - ./dist/firefox-extension

Compile Chrome:
  stage: compiling
  script:
    - mkdir dist
    - npm install
    - npm run build:chrome
    - mv build dist/chrome-extension
  artifacts:
    paths:
      - ./dist/chrome-extension

Publish Nightly Firefox:
  stage: publishing
  script:
    - 'export ARTIFACT_URL=${CI_PROJECT_URL}/-/jobs/artifacts/${CI_COMMIT_BRANCH}/raw/dist/firefox-extension/FILE?job=Compile+Firefox'
    - 'sed -i -e "s|\"gecko\": {|\"gecko\":{\"update_url\":\"ARTIFACT_URL\",|g" ./dist/firefox-extension/manifest.json'
    - 'sed -i -e "s|BUILD|${CI_PIPELINE_ID}|g" ./dist/firefox-extension/manifest.json'
    - 'sed -i -e "s|ARTIFACT_URL|${ARTIFACT_URL}|g" ./dist/firefox-extension/manifest.json'
    - 'sed -i -e "s|FILE|updates.json|g" ./dist/firefox-extension/manifest.json'
    - 'sed -i -e "s|BUILD|${CI_PIPELINE_ID}|g" ./dist/firefox-extension/updates.json'
    - 'sed -i -e "s|ARTIFACT_URL|${ARTIFACT_URL}|g" ./dist/firefox-extension/updates.json'
    - 'sed -i -e "s|FILE|extension.xpi|g" ./dist/firefox-extension/updates.json'
    - 'npx web-ext sign --channel unlisted'
  environment:
    name: Testing
  only:
    - testing

Publish Nightly Chrome:
  stage: publishing
  script:
    - 'export WEXT_SHIPIT_CHROME_EXTENSION_ID=${CHROME_EXTENSION_ID_TESTING}'
    - 'sed -i -e "s|99999|${CI_PIPELINE_ID}|g" ./dist/chrome-extension/manifest.json'
    - 'npx @wext/shipit chrome dist/chrome-extension'
  environment:
    name: Testing
  only:
    - testing

Publish Stable Firefox:
  stage: publishing
  script:
    - 'rm dist/firefox-extension/updates.json'
    - 'sed -i -e "s|BUILD||g" ./dist/firefox-extension/manifest.json'
    - 'npx @wext/shipit firefox dist/firefox-extension'
  environment:
    name: Stable
  only:
    - stable

Publish Stable Chrome:
  stage: publishing
  script:
    - 'export WEXT_SHIPIT_CHROME_EXTENSION_ID=${CHROME_EXTENSION_ID_STABLE}'
    - 'sed -i -e "s|99999||g" ./dist/chrome-extension/manifest.json'
    - 'npx @wext/shipit chrome dist/chrome-extension'
  environment:
    name: Stable
  only:
    - stable