stages:
- prepare
- compiling
- publishing

Install:
  stage: prepare
  script:
  - mkdir dist
  artifacts:
    paths:
    - ./dist

Compile Firefox:
  stage: compiling
  script:
  - npm install
  - npm run build:firefox
  - sed -i -e "s/BUILD/${CI_PIPELINE_ID}/g" ./build/manifest.json
  - if [ "${CI_COMMIT_REF_NAME}" != "stable" ] ; then sed -i -e "s/ncpasswords@mdns.eu/ncpasswordsdev@mdns.eu/g" ./build/manifest.json ; fi
  - mv build dist/firefox-extension
  artifacts:
    paths:
    - ./dist/firefox-extension

Compile Chrome:
  stage: compiling
  script:
  - npm install
  - npm run build:chrome
  - sed -i -e "s/99999/${CI_PIPELINE_ID}/g" ./build/manifest.json
  - mv build dist/chrome-extension
  artifacts:
    paths:
    - ./dist/chrome-extension

Publish Stable Firefox:
  stage: publishing
  script:
    - 'npx @wext/shipit firefox dist/firefox-extension'
  environment:
    name: Stable
  only:
    - tags

Publish Stable Chrome:
  stage: publishing
  script:
    - 'npx @wext/shipit chrome dist/chrome-extension'
  environment:
    name: Stable
  only:
    - tags