stages:
- prepare
- compiling
- publishing

Install:
  stage: prepare
  script:
  - mkdir dist
  artifacts:
    paths:
    - ./dist

Compile Firefox:
  stage: compiling
  script:
  - npm install
  - npm run build:firefox
  - sed -i -e "s/BUILD/${CI_PIPELINE_ID}/g" ./build/manifest.json
  - mv build dist/firefox-extension
  artifacts:
    paths:
    - ./dist

Compile Chrome:
  stage: compiling
  script:
  - npm install
  - npm run build:chrome
  - sed -i -e "s/BUILD/${CI_PIPELINE_ID}/g" ./build/manifest.json
  - mv build dist/chrome-extension
  artifacts:
    paths:
    - ./dist

Publish Stable:
  stage: publishing
  script:
    - 'npx shipit firefox dist/firefox-extension'
    - 'npx shipit chrome dist/chrome-extension'
  environment:
    name: Stable
  only:
    - tags