blank_issues_enabled: false
contact_links:
  - name: Community Forum
    url: https://help.nextcloud.com/c/apps/passwords
    about: Get support with problems you have
  - name: Telegram Chat
    url: https://t.me/nc_passwords
    about: Ask questions and discuss with other users
  - name: Official Nextcloud App Bugtracker
    url: https://github.com/marius-wieschollek/passwords/issues
    about: Report issues or request a feature for the Nextcloud app